owner: LynPtl
repo: LynPtl.github.io
sites:
  - name: Blog
    url: https://lynptl.github.io/
status-website:
  cname: # status.yourdomain.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: LynPtl's Blog Status
  introTitle: "This is the status page for LynPtl's Blog."
  introMessage: "It uses Upptime to monitor the site's availability and performance."
  navbar:
    - title: Blog
      url: https://lynptl.github.io/
workflowSchedule:
  uptime: "*/5 * * * *"
