<div class="footer-links" style="text-align: center;">
  <span>友情链接: </span>
  <a href="https://involutionhell.com/" target="_blank" rel="noopener">内卷地狱</a> |
  <a href="https://shouw.blog/" target="_blank" rel="noopener">index</a> |
  <a href="https://space.bilibili.com/2051805852" target="_blank" rel="noopener">发哥的云计算课堂</a> |
  <a href="https://space.bilibili.com/351510324" target="_blank" rel="noopener">黑兔由帝</a>
</div>
